// Do not edit. This file is machine generated by the Resource DLL Wizard.

library _QrCode;

{ITE} {LCID:00000416:00000416} {}
{ITE} {DFMFileType} {Funcoes\uFuncoesQrCode.dfm}
{ITE} {RCFileType} {_QrCode_DRC.rc}

{$R 'Funcoes\uFuncoesQrCode.dfm' Form1:TForm}
{$R '_QrCode_DRC.res' '_QrCode_DRC.rc'}

{$E PTB}

begin
end.